#!/bin/bash

read -p "Enter a 4-digit integer: " input

# Check if the input is a 4-digit integer
if [[ $input =~ ^[0-9]{4}$ ]]; then
    hash=$(echo -n "$input" | sha256sum | awk '{print $1}')
    echo "Hash of $input: $hash"
    echo "Saving hash to file 'hash_output.txt'"
    echo "$hash" > hash_output.txt

else
    echo "Invalid input. Please enter a 4-digit integer."
fi
