#!/usr/bin/env bash

spawner(){
    # Check the number of arguments
    if [ "$#" -ne 3 ]; then
        #echo "Error: Invalid number of arguments passed to spawner()"
        exit 2
    fi

    memoryInKB=$1
    timeoutInSec=$2
    binaryName=$3

    # Check if the binary exists
    if [ ! -f "$binaryName" ]; then
        #echo "Error: $binaryName doesn't exist"
        exit 3
    fi

    # Check if the binary has the execute flag
    if [ ! -x "$binaryName" ]; then
        #echo "Error: $binaryName doesn't have +x flag"
        exit 4
    fi

    # Run the binary in the background
    ./"$binaryName" &
    pid=$!

    # Monitor memory usage of the binary
    while true; do
        memUsage=$(pmap -x "$pid" | tail -n 1 | awk "{print \$3}")
        memUsage=${memUsage%%K*}

        if [ "$memUsage" -gt "$memoryInKB" ]; then
            #echo "Error: $binaryName exceeded the memory limit"
            kill "$pid"
            exit 1
        fi
        
        # Check if the binary has exceeded the timeout limit
        if ! timeout "$timeoutInSec" time -f "%e" ./"$binaryName"; then
            #echo "Error: $binaryName exceeded the timeout limit"
            kill "$pid"
            exit 5
        fi
        
        # Check if the binary has finished
        if ! ps -p "$pid" > /dev/null; then
            break
        fi

        sleep 1
    done

}


